cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'romkatv/powerlevel10k'

brew 'grep'
brew 'openssh'
brew 'screen'
brew 'zsh'
brew 'zplug'
brew 'git'
brew 'git-lfs'
brew 'yarn'
brew 'nvm'
brew 'docker'
brew 'vim', args: ['with-override-system-vi']
brew 'the_silver_searcher'
brew 'powerlevel10k'
brew 'gh'
brew 'curl'
brew 'font-fira-code-nerd-font'
brew 'font-hack-nerd-font'
brew 'font-meslo-lg-nerd-font'

cask 'sequel-pro'
cask 'java'
cask 'iterm2'
cask 'visual-studio-code'
cask 'google-chrome'
cask 'firefox'
cask 'spectacle'
cask 'slack'
cask 'spotify'
cask 'microsoft-edge'
